# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hp-oga-_YHYvDKOQZQa6Wi6RRJ1S6ah0
"""

import asyncio
import json
import os
from typing import Optional
from fastapi import FastAPI, HTTPException
from fastapi.openapi.docs import get_swagger_ui_html
from pydantic import BaseModel
from starlette.responses import StreamingResponse, FileResponse
from starlette.staticfiles import StaticFiles

from realtime_asr.filtering import get_word_manager, get_prompt_manager
from realtime_asr.translator import OllamaTranslator, LlamaTranslator, TranslatorBase
from realtime_asr.config import PROJECT_ROOT, DIST_PATH


def create_app(recording_event, transcript_list, model_info, db_reset) -> FastAPI:
    root_path = PROJECT_ROOT
    build_path = DIST_PATH

    app = FastAPI(docs_url=None)
    app.openapi_version = "3.0.0"
    app.mount(
        "/static",
        StaticFiles(directory=os.path.join(root_path, "frontend", "static")),
        name="static",
    )

    app.mount(
        "/assets",
        StaticFiles(directory=os.path.join(build_path, "assets")),
        name="assets",
    )

    if model_info.serve == "ollama":
        model = OllamaTranslator(model_info.name)
    elif model_info.serve == "llama":
        model = LlamaTranslator(model_info.name)
    else:
        raise TypeError(f"Unknown model serve type: {model_info.serve}")

    app.state.translator = model
    app.state.db_reset = db_reset

    @app.on_event("startup")
    async def startup_event():
        await app.state.translator.connect()

    @app.on_event("shutdown")
    async def shutdown_event():
        await app.state.translator.close()

    focus_flag = 0

    async def generate_stream():
        nonlocal focus_flag
        while True:
            result_list = transcript_list.get()
            transcript_list.put_nowait(result_list)
            # print(result_list)

            if result_list:
                if focus_flag >= len(result_list):
                    await asyncio.sleep(0.1)
                    continue
                # focus_flag = max(focus_flag, len(result_list) - 5)
                target = result_list[focus_flag]
                content, spk, completed = target.content, target.spk, target.completed
                language, status = spk.value, TranslatorBase.get_status(completed)

                if not language:
                    await asyncio.sleep(0.1)
                    if completed:
                        focus_flag += 1
                    continue

                if not completed:
                    # print(dict(content=content, language=language, status=status))
                    yield f"data: {json.dumps(dict(content=content, language=language, status=status), ensure_ascii=False)}\n\n"
                    await asyncio.sleep(0.1)
                else:
                    # print(dict(content=content, language=language, status=status))
                    yield f"data: {json.dumps(dict(content=content, language=language, status=status), ensure_ascii=False)}\n\n"
                    await asyncio.sleep(0.1)

                    focus_flag += 1

            if not recording_event.is_set():
                transcript_list.get()
                transcript_list.put_nowait([])
                break

    class TranslateRequest(BaseModel):
        content: str
        language: str
        completed: bool = False

    @app.get("/api/recordings")
    async def recording():
        if not recording_event.is_set():
            raise HTTPException(
                status_code=409,
                detail={
                    "error": "No active recording in progress. Cannot receive data."
                },
            )
        return StreamingResponse(generate_stream(), media_type="text/event-stream")

    @app.post("/api/translate")
    async def translate(request: TranslateRequest):
        # print(f"Request content: {request.content}") # translate 요청문장
        return StreamingResponse(
            app.state.translator.translate(request.content, request.language),
            media_type="text/event-stream",
        )

    @app.get("/api/recordings/start")
    def start_recording():
        if recording_event.is_set():
            raise HTTPException(
                status_code=409, detail={"error": "Recording already in progress."}
            )
        recording_event.set()

        return {"status": "recording"}

    @app.get("/api/recordings/stop")
    def stop_recording():
        if not recording_event.is_set():
            raise HTTPException(
                status_code=409,
                detail={"error": "No active recording in progress to stop."},
            )
        recording_event.clear()

        nonlocal focus_flag
        focus_flag = 0

        transcript_list.get()
        transcript_list.put_nowait([])

        return {"status": "stopped"}

    @app.get("/api/recordings/status")
    def status_recording():
        status = "recording" if (recording_event.is_set()) else "stopped"
        return {"status": status}

    @app.get("/docs", include_in_schema=False)
    def custom_swagger_ui_html():
        return get_swagger_ui_html(
            openapi_url=app.openapi_url,
            title=app.title + " - Swagger UI",
            swagger_js_url=os.path.join(root_path, "static", "swagger-ui-bundle.js"),
            swagger_css_url=os.path.join(root_path, "static", "swagger-ui.css"),
            swagger_favicon_url=os.path.join(root_path, "static", "favicon.ico"),
        )

    # =================================================================
    # filtering을 위한 api 엔드포인트 추가 부분
    class CorrectionUpdate(BaseModel):
        wrong_word: str
        correct_word: str

    # 1. 조회: 현재 적용된 모든 단어 쌍(base + user) 확인
    @app.get("/api/corrections")
    async def get_corrections():
        word_manager = get_word_manager()
        return word_manager.user_replacements #

    # 2. 추가/수정: 사용자 정의 단어 추가 (추가 후 자동 정렬/병합)
    @app.post("/api/corrections")
    async def add_correction(item: CorrectionUpdate):
        word_manager = get_word_manager()
        word_manager.add_user_word(item.wrong_word, item.correct_word)
        app.state.db_reset.set()
        return {"status": "success"}

    # 3. 삭제: 사용자 정의 단어 삭제
    @app.delete("/api/corrections/{wrong_word}")
    async def delete_correction(wrong_word: str):
        word_manager = get_word_manager()
        word_manager.delete_user_word(wrong_word)
        app.state.db_reset.set()
        return {"status": "success"}

    # =================================================================
    # [API] 프롬프트 데이터 관리 (Glossary & Sentence)

    class PromptItemRequest(BaseModel):
        block_key: str  # "glossary_block" 또는 "sentence_block"
        origin: str  # 원본 (Key)
        translation: Optional[str] = None  # 번역(Value) - 삭제 시에는 무시됨

    @app.get("/api/prompts")
    async def get_prompts():
        """
        [User View]
        - Glossary: 사용자 추가 항목만 반환 (개발자 기본값 숨김)
        - Sentence: 전체(기본+수정) 반환
        """
        prompt_manager = get_prompt_manager()
        return prompt_manager.get_user_view_settings()

    # 2. 추가/수정 (POST)
    @app.post("/api/prompts/add-item")
    async def add_prompt_item(request: PromptItemRequest):
        if request.block_key not in ["glossary_block", "sentence_block"]:
            return {"status": "error", "message": "Invalid block key"}

        prompt_manager = get_prompt_manager()
        prompt_manager.add_item(request.block_key, request.origin, request.translation)
        return {"status": "success", "message": "Item saved"}

    # 3. 삭제 (POST - Delete Item)
    @app.post("/api/prompts/delete-item")
    async def delete_prompt_item(request: PromptItemRequest):
        if request.block_key not in ["glossary_block", "sentence_block"]:
            return {"status": "error", "message": "Invalid block key"}

        prompt_manager = get_prompt_manager()
        success = prompt_manager.remove_item(request.block_key, request.origin)

        if success:
            return {"status": "success", "message": "Item deleted"}
        else:
            # 사용자가 추가한 단어가 아니거나 (Glossary), 키가 없을 때
            return {
                "status": "warning",
                "message": "Item not found or cannot delete default glossary item",
            }

    # =================================================================

    @app.get("/{full_path:path}")
    async def serve_react(full_path: str):
        index_file = os.path.join(build_path, "index.html")
        return FileResponse(index_file)

    return app