# -*- coding: utf-8 -*-
"""(filtering/)__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGd-CfqSFnazJShXrdb48eOZYTNOrwlP
"""

import json
import re
import os

from realtime_asr.filtering.manager import WordCorrectionManager
from realtime_asr.filtering.prompt_manager import TranslationPromptManager
from realtime_asr.config import PROJECT_ROOT

# 1. 단어 오인식 교정 매니저
_word_manager = None

def get_word_manager():
    global _word_manager
    if _word_manager is None:
        _word_manager = WordCorrectionManager(
            base_json_path = os.path.join(
                PROJECT_ROOT, "configs", "admin_replacement.json"
            ),
            db_path = os.path.join(PROJECT_ROOT, "configs", "user_replacement.db"),
        )
    return _word_manager


# 2. 번역 프롬프트 매니저 (User Correction DB 공유)
_prompt_manager = None

def get_prompt_manager():
    global _prompt_manager
    if _prompt_manager is None:
        _prompt_manager = TranslationPromptManager(
            base_json_path = os.path.join(
                PROJECT_ROOT, "configs", "admin_translation_glossary.json"
            ),
            db_path = os.path.join(PROJECT_ROOT, "configs", "user_translation_glossary.db"),
        )
    return _prompt_manager

def _load_hallucination_json():
    """hallucination.json은 변동이 거의 없으므로 최초 한번만 로드"""
    file_path = PROJECT_ROOT / "configs" / "hallucination.json"
    if not os.path.exists(file_path):
        return []
    with open(file_path, "r", encoding="utf-8") as f:
        data = list(json.load(f))
        # 💡 [추가] 길이가 긴 단어부터 먼저 필터링되도록 내림차순 정렬
        return sorted(data, key=len, reverse=True)

_HALLUCINATIONS = _load_hallucination_json()



def filter_hallucination(raw_transcript: list) -> list:
    """
    hallucination.json 에 정의된 불필요 토큰 삭제
    WordCorrectionManager.combined_replacements 로 단어 교정
    반환 형식 [(start, end, text), ...] (whisperlive 기존 형태 유지)
    """
    if not raw_transcript:
        return []

    filtered = []
    for segment in raw_transcript:
        seg = list(segment)
        for bad_token in _HALLUCINATIONS:
            if bad_token in seg[2]:
                seg[2] = seg[2].replace(bad_token, "")

        # 💡 [추가] 환각 단어 제거 후 남은 다중 공백 찌꺼기를 단일 공백으로 청소 및 양끝 공백 제거
        seg[2] = re.sub(r'\s+', ' ', seg[2]).strip()

        txt = seg[2].strip()
        if txt and txt not in {".","?"} and set(txt) != {"."}:
            filtered.append(seg)

    word_manager = get_word_manager()
    replacements = word_manager.combined_replacements
    if replacements:
        # 길이가 긴 키부터 매칭하도록 정렬된 dict 사용 -> 이미 manager에서 정렬돼 있음
        pattern = re.compile("|".join(re.escape(k) for k in replacements.keys()))
        for seg in filtered:
            seg[2] = pattern.sub(lambda m: replacements[m.group(0)], seg[2])

    return [tuple(seg) for seg in filtered]