# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADlgSEJgyj5RkK0G37zy5ygfyn2IKWSC
"""

import argparse
import logging
import multiprocessing as mp
import os
import signal
import sys
import time
import asyncio
import psutil
import uvicorn
from datetime import datetime
from functools import partial
from multiprocessing import Process, Event, Queue

from realtime_asr.app import create_app
from realtime_asr.translator import ModelInfo
from realtime_asr.config import init_settings, PROJECT_ROOT


def log_system_resources():
    log_dir = PROJECT_ROOT / "logs"
    os.makedirs(log_dir, exist_ok=True)
    log_time = datetime.now().strftime("%Y%m%d_%H%M%S")

    # 로그 설정 (INFO레벨)
    logging.basicConfig(
        filename=os.path.join(log_dir, f"resource-log.{log_time}.log"),
        level=logging.INFO,
    )

    print("Start log_system_resources!!")

    while True:
        current_time = datetime.now().strftime("%Y-%m-%d_%H:%M:%S")
        cpu_usage = psutil.cpu_percent(interval=1)
        memory_info = psutil.virtual_memory().percent

        log_message = (
            f"Time: {current_time}\n"
            f"CPU Usage: {cpu_usage}%\n"
            f"Memory Usage: {memory_info}%\n"
        )
        logging.info(log_message)
        time.sleep(300)


def asr_process(config_path: str):
    try:
        settings = init_settings(config_path)
    except (FileNotFoundError, ValueError) as e:
        print(f"[ERROR] configs file load failed: {e}")
        return

    from realtime_asr.WhisperLive.server import TranscriptionServer

    server = TranscriptionServer()

    try:
        asyncio.run(
            server.run(
                "0.0.0.0",
                faster_whisper_custom_model_path="models/faster-whisper-large-v3-turbo",
                port=settings["port"],
            )
        )
    except Exception as e:
        print("[Server Error]: ", e)
        server.cleanup("0.0.0.0")


def audio_receiver(
    config_path: str, recording_event, reset, transcript_list, db_reset
):
    try:
        settings = init_settings(config_path)
    except (FileNotFoundError, ValueError) as e:
        print(f"[ERROR] configs file load failed: {e}")
        return

    from realtime_asr.WhisperLive.client import TranscriptionClient

    # mp3 저장 파일명 : YYMMDD_HHMM_RIVE
    # (ex. 250319_1352_RIVE.mp3, 250319_1352_RIVE.wav) # 번역중 색깔
    start_time = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_name = os.path.join(
        PROJECT_ROOT, "output", "audio", f"output_audio_{start_time}.wav"
    )
    x = 0

    client = None
    while x < 30:  # max number of retrial
        cpu_usage = psutil.cpu_percent(interval=1.5)
        print(f"\nCPU usage: {cpu_usage}%\n")
        x += 1
        if cpu_usage < 30:
            client = TranscriptionClient(
                "localhost",
                settings["port"],
                recording_event,
                reset,
                db_reset,
                transcript_list,
                output_recording_filename=file_name,
                lang=None,  # lang을 정하지 않은 상태로
                translate=False,
                hotwords=None,
                save_output_recording=False,
                max_clients=3,
                max_connection_time=600000000,
            )
            break
    if x == 30:
        print("Failed Connecting")

    try:
        client()
    except Exception:
        client.close()


def run_api(config_path: str, recording_event, transcript_list, db_reset):
    try:
        settings = init_settings(config_path)
    except (FileNotFoundError, ValueError) as e:
        print(f"[ERROR] configs file load failed: {e}")
        exit(1)

    model_info = ModelInfo(settings["model_serve"], settings["model_name"])

    app = create_app(recording_event, transcript_list, model_info, db_reset)
    uvicorn.run(app, host="0.0.0.0", port=8000)


def signal_handler(process_list, sig, frame):
    print("Signal Handler Called")
    for process in process_list:
        if process.is_alive():
            process.terminate()
    sys.exit(0)


def entry_point():
    ctx = mp.get_context('spawn')
    Process = ctx.Process
    Event = ctx.Event
    Queue = ctx.Queue

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-c",
        "--config",
        type=str,
        default="whisper_1023.yaml",
        help="config file path (default: whisper_1023.yaml)",
    )
    args = parser.parse_args()
    config_path = args.config

    recording_event = Event()
    reset = Event()
    db_reset = Event()
    transcript_list = Queue(3)  # readonly 포함, 화면에 보여지는 transcript
    transcript_list.put_nowait([])

    process_list = [
        Process(
            target=audio_receiver,
            args=(config_path, recording_event, reset, transcript_list, db_reset),
        ),
        Process(target=asr_process, args=(config_path,)),
        Process(
            target=run_api,
            args=(config_path, recording_event, transcript_list, db_reset),
        ),
    ]

    signal.signal(signal.SIGINT, partial(signal_handler, process_list))

    try:
        # resource_logger.start() # logging 전용이라서, 따로 시작(관리용)
        for process in process_list:
            process.start()

        for process in process_list:
            process.join()
    except Exception as e:
        print(e)
        for process in process_list:
            if process.is_alive():
                process.terminate()
        sys.exit(1)


if __name__ == "__main__":
    entry_point()