# -*- coding: utf-8 -*-
"""prompt_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVXxWES8h9NdbTwPNqks5Mjz_K-vZodf
"""

import sqlite3
import json
import os

class TranslationPromptManager:
    def __init__(self, base_json_path,db_path):
        self.db_path = db_path

        # 블록 헤더 정의
        self.headers = {
            "glossary_block": "GLOSSARY(Term:Translation)",
            "sentence_block": "### EXAMPLES"
        }

        # 개발자 기본값 세팅
        self.defaults = {
            "glossary_block": self._load_default_glossary_from_file(base_json_path),
            "sentence_block": {
                "The ROK Air Force conducted joint air operations": "대한민국 공군은 연합 공중작전을 수행했다.",
                "보고를 드리기 전 안내 말씀드리겠습니다.": "Before we begin, a brief notice.",
                "우리는 한미 연합 공중훈련의 일환으로 대한민국(ROK) 공군 부대와 협조했다", "We cordinated with ROK Air Force unit as part of ROK-US combined air exercise."
            }
        }

        # 사용자 설정 캐시
        # glossary_block: 사용자 추가 용어 (기본값과 병합됨)
        # sentence_block: None이면 기본값 사용, 값이 있으면 전체 덮어쓰기 (Copy-on-Write)
        self.user_settings = {
            "glossary_block": {},
            "sentence_block": None
        }

        self._init_db()
        self.load_settings()

    # ------------------------------------------------------------------
    # [초기화 및 DB 관리]
    # ------------------------------------------------------------------
    def _load_default_glossary_from_file(self) -> dict:
        """JSON 파일에서 개발자 기본 용어집 로드 (실패 시 빈 딕셔너리 반환)"""
        try:
            if os.path.exists(file_path):
                with open(file_path, 'r', encoding='utf-8') as f:
                    return json.load(f)
            return {}
        except Exception as e:
            print(f"Warning : Failed to load default glossary: {e}")
            return {}

    def _init_db(self):
        """SQLite DB 초기화"""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS prompt_settings (
                    key TEXT PRIMARY KEY,
                    value TEXT -- JSON String
                )
            ''')
            conn.commit()

    def load_settings(self):
        """DB에서 사용자 설정 로드"""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT key, value FROM prompt_settings")
            rows = cursor.fetchall()

            for key, val_str in rows:
                if key in self.user_settings:
                    try:
                        self.user_settings[key] = json.loads(val_str)
                    except json.JSONDecodeError:
                        self.user_settings[key] = (
                            {} if key == "glossary_block" else None
                        )

    def _save_to_db(self, key: str):
        """메모리 설정을 DB에 저장"""
        val = self.user_settings[key]
        if val is None:
            return

        json_val = json.dumps(val, ensure_ascii=False)
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("INSERT OR REPLACE INTO prompt_settings (key, value) VALUES (?, ?)", (key, json_val))
            conn.commit()

    # ------------------------------------------------------------------
    # [데이터 추가/삭제/조회 API 연동용]
    # ------------------------------------------------------------------
    def add_item(self, block_key: str, origin: str, translation: str):
        if block_key == "glossary_block":
            self.user_settings["glossary_block"][origin.strip()] = translation.strip()
            self._save_to_db("glossary_block")
        elif block_key == "sentence_block":
            if self.user_settings["sentence_block"] is None:
                self.user_settings["sentence_block"] = self.defaults["sentence_block"].copy()
            self.user_settings["sentence_block"][origin.strip()] = translation.strip()
            self._save_to_db("sentence_block")
        return True

    def remove_item(self, block_key: str, origin: str):
        target_key = origin.strip()
        if block_key == "glossary_block":
            if target_key in self.user_settings["glossary_block"]:
                del self.user_settings["glossary_block"][target_key]
                self._save_to_db("glossary_block")
                return True
            else:
                return False
        elif block_key == "sentence_block":
            if self.user_settings["sentence_block"] is None:
                self.user_settings["sentence_block"] = self.defaults["sentence_block"].copy()
            if target_key in self.user_settings["sentence_block"]:
                del self.user_settings["sentence_block"][target_key]
                self._save_to_db("sentence_block")
                return True
        return False

    def get_user_view_settings(self):
        """프론트엔드 표출용 데이터 반환 (개발자 용어집 숨김)"""
        current_sentence = self.user_settings["sentence_block"]
        if current_sentence is None:
            current_sentence = self.defaults["sentence_block"]
        return {
            "glossary_block": self.user_settings["glossary_block"],
            "sentence_block": current_sentence
        }

    # ------------------------------------------------------------------
    # [프롬프트 동적 주입용]
    # ------------------------------------------------------------------
    def get_relevant_glossary(self, input_text: str) -> str:
        """
        [로직 반영]
        1. 단순 in 매칭 (조사 문제 해결)
        2. 양방향 검색 (한->영, 영->한 모두 매칭)
        3. 매칭된 단어가 없을 시 빈 문자열 반환 (빈 헤더 방지)
        """
        combined_glossary = self.defaults["glossary_block"].copy()
        combined_glossary.update(self.user_settings["glossary_block"])

        if not combined_glossary:
            return ""

        relevant_items = []
        input_lower = input_text.lower()

        for origin, trans in combined_glossary.items():
            match_origin = origin.lower() in input_lower
            match_trans = trans.lower() in input_lower
            if match_origin or match_trans:
                relevant_items.append(f"{origin} : {trans}")

        if not relevant_items:
            return ""

        return f"{self.headers['glossary_block']}\n" + "\n".join(relevant_items)

    def get_sentence_block(self) -> str:
        """예시 문장 전체 반환 (없을 시 빈 문자열 반환)"""
        current_dict = self.user_settings["sentence_block"]
        if current_dict is None:
            current_dict = self.defaults["sentence_block"]

        if not current_dict:
            return ""

        items = []
        for inp, out in current_dict.items():
            items.append(f"- INPUT : {inp}\n- OUTPUT : {out}")

        return f"{self.headers['sentence_block']}\n" + "\n\n".join(items)