# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flP_d1vU8QjbxewzdJdPtHpOk9d8kXPC
"""

import functools
import json
import logging
import os
import threading
import time
import traceback
import asyncio
from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any

import numpy as np
import torch
from websockets.exceptions import ConnectionClosed
from websockets.server import serve

from realtime_asr.WhisperLive.transcriber import WhisperModel
from realtime_asr.config import SETTINGS, PROJECT_ROOT

logging.basicConfig(level=logging.INFO)

class ClientManager:
    def __init__(self, max_clients=4, max_connection_time=600):
        """
        Initializes the ClientManager with specified limits on client connections and connection durations.

        Args:
            max_clients (int, optional): The maximum number of simultaneous client connections allowed. Defaults to 4.
            max_connection_time (int, optional): The maximum duration (in seconds) a client can stay connected. Defaults
                                                 to 600 seconds (10 minutes).
        """
        self.clients = {}
        self.start_times = {}
        self.max_clients = max_clients
        self.max_connection_time = max_connection_time

    def add_client(self, websocket, client):
        """
        Adds a client and their connection start time to the tracking dictionaries.

        Args:
            websocket: The websocket associated with the client to add.
            client: The client object to be added and tracked.
        """
        self.clients[websocket] = client
        self.start_times[websocket] = time.time()

    def get_client(self, websocket):
        """
        Retrieves a client associated with the given websocket.

        Args:
            websocket: The websocket associated with the client to retrieve.

        Returns:
            The client object if found, False otherwise.
        """
        if websocket in self.clients:
            return self.clients[websocket]
        return False

    def remove_client(self, websocket):
        """
        Removes a client and their connection start time from the tracking dictionaries. Performs cleanup on the
        client if necessary.

        Args:
            websocket: The websocket associated with the client to be removed.
        """
        client = self.clients.pop(websocket, None)
        if client:
            client.cleanup()
        self.start_times.pop(websocket, None)

    def get_wait_time(self):
        """
        Calculates the estimated wait time for new clients based on the remaining connection times of current clients.

        Returns:
            The estimated wait time in minutes for new clients to connect. Returns 0 if there are available slots.
        """
        wait_time = None
        for start_time in self.start_times.values():
            current_client_time_remaining = self.max_connection_time - (time.time() - start_time)
            if wait_time is None or current_client_time_remaining < wait_time:
                wait_time = current_client_time_remaining
        return wait_time / 60 if wait_time is not None else 0

    async def is_server_full(self, websocket, options):
        """
        Checks if the server is at its maximum client capacity and sends a wait message to the client if necessary.

        Args:
            websocket: The websocket of the client attempting to connect.
            options: A dictionary of options that may include the client's unique identifier.

        Returns:
            True if the server is full, False otherwise.
        """
        if len(self.clients) >= self.max_clients:
            wait_time = self.get_wait_time()
            response = {"uid": options["uid"], "status": "WAIT", "message": wait_time}
            websocket.send(json.dumps(response))
            return True
        return False

    async def is_client_timeout(self, websocket):
        """
        Checks if a client has exceeded the maximum allowed connection time and disconnects them if so, issuing a warning.

        Args:
            websocket: The websocket associated with the client to check.

        Returns:
            True if the client's connection time has exceeded the maximum limit, False otherwise.
        """
        elapsed_time = time.time() - self.start_times[websocket]
        if elapsed_time >= self.max_connection_time:
            await self.clients[websocket].disconnect()
            logging.warning(f"Client with uid '{self.clients[websocket].client_uid}' disconnected due to overtime.")
            return True
        return False


class BackendType(Enum):
    FASTER_WHISPER = "faster_whisper"

    @staticmethod
    def valid_types() -> List[str]:
        return [backend_type.value for backend_type in BackendType]

    @staticmethod
    def is_valid(backend: str) -> bool:
        return backend in BackendType.valid_types()

    def is_faster_whisper(self) -> bool:
        return self == BackendType.FASTER_WHISPER

class TranscriptionServer:
    RATE = 16000

    def __init__(self):
        self.client_manager = None
        self.single_model = False

    async def initialize_client(
        self, websocket, options, faster_whisper_custom_model_path
    ):
        client: Optional[ServeClientBase] = None

        try:
            if self.backend.is_faster_whisper():
                if faster_whisper_custom_model_path is not None and os.path.exists(faster_whisper_custom_model_path):
                    logging.info(f"Using custom model {faster_whisper_custom_model_path}")
                    options["model"] = faster_whisper_custom_model_path
                    print(f"\nASR options : {options}\n")
                client = ServeClientFasterWhisper(
                    websocket,
                    language=options["language"],
                    task=options["task"],
                    client_uid=options["uid"],
                    model=options["model"],
                    hotwords = options.get("hotwords"),
                    single_model=self.single_model,
                )
                asyncio.create_task(client.init_stt_thread())
        except Exception as e:
            print(f"ServeClientFasterWhisper init Error: {e}")
            logging.error(e)
            return

        if client is None:
            raise ValueError(f"Backend type {self.backend.value} not recognised or not handled.")

        self.client_manager.add_client(websocket, client)

    async def get_audio_from_websocket(self, websocket):
        """
        Receives audio buffer from websocket and creates a numpy array out of it.

        Args:
            websocket: The websocket to receive audio from.

        Returns:
            A numpy array containing the audio.
        """
        async for message in websocket:
          frame_data = message
          break
        if frame_data == b"END_OF_AUDIO":
            return False
        if frame_data == "reset":
          client = self.client_manager.get_client(websocket)
          client.data_reset() # 여기에서 client에서 data 초기화됨
          return True
        return np.frombuffer(frame_data, dtype=np.float32)

    async def handle_new_connection(self, websocket, faster_whisper_custom_model_path):
        try:
            logging.info("New client connected")
            options = await websocket.recv()
            options = json.loads(options)

            if self.client_manager is None:
              max_clients = options.get("max_clients",4)
              max_connection_time = options.get("max_connection_time", 600)
              self.client_manager = ClientManager(max_clients, max_connection_time)

            if await self.client_manager.is_server_full(websocket, options):
                websocket.close()
                return False  # Indicates that the connection should not continue

            await self.initialize_client(websocket, options, faster_whisper_custom_model_path)
            return True

        except json.JSONDecodeError:
            logging.error("Failed to decode JSON from client")
            return False
        except ConnectionClosed:
            logging.info("Connection closed by client")
            return False
        except Exception as e:
            logging.error(f"Error during new connection initialization: {str(e)}")
            return False

    async def process_audio_frames(self, websocket):
        frame_np = await self.get_audio_from_websocket(websocket)
        client = self.client_manager.get_client(websocket)
        if frame_np is False:
            return False
        elif frame_np is True:
            return True

        client.add_frames(frame_np)
        return True

    async def recv_audio(self,
                   websocket,
                   backend: BackendType = BackendType.FASTER_WHISPER,
                   faster_whisper_custom_model_path=None,):
        """
        Receive audio chunks from a client in an infinite loop.

        Continuously receives audio frames from a connected client
        over a WebSocket connection. It processes the audio frames using a
        voice activity detection (VAD) model to determine if they contain speech
        or not. If the audio frame contains speech, it is added to the client's
        audio data for ASR.
        If the maximum number of clients is reached, the method sends a
        "WAIT" status to the client, indicating that they should wait
        until a slot is available.
        If a client's connection exceeds the maximum allowed time, it will
        be disconnected, and the client's resources will be cleaned up.

        Args:
            websocket (WebSocket): The WebSocket connection for the client.
            backend (str): The backend to run the server with.
            faster_whisper_custom_model_path (str): path to custom faster whisper model.
            whisper_tensorrt_path (str): Required for tensorrt backend.
            trt_multilingual(bool): Only used for tensorrt, True if multilingual model.

        Raises:
            Exception: If there is an error during the audio frame processing.
        """
        self.backend = backend
        if not await self.handle_new_connection(
            websocket, faster_whisper_custom_model_path):
            return

        try:
            while not await self.client_manager.is_client_timeout(websocket):
                if not await self.process_audio_frames(websocket):
                    break
                await asyncio.sleep(0)
        except ConnectionClosed:
            logging.info("Connection closed by client")
        except Exception as e:
            logging.error(f"Unexpected error: {str(e)}")
        finally:
            if self.client_manager.get_client(websocket):
                self.cleanup(websocket)
                await websocket.close()
            del websocket

    async def run(self,
            host,
            port=9090,
            backend="faster_whisper",
            faster_whisper_custom_model_path=None,
            single_model=True,):


        """
        Run the transcription server.

        Args:
            host (str): The host address to bind the server.
            port (int): The port number to bind the server.
        """

        if faster_whisper_custom_model_path is not None and not os.path.exists(faster_whisper_custom_model_path):
            raise ValueError(f"Custom faster_whisper model '{faster_whisper_custom_model_path}' is not a valid path or HuggingFace model.")

        if single_model:
            if faster_whisper_custom_model_path:
                logging.info("Custom model option was provided. Switching to single model mode.")
                self.single_model = True
                # TODO: load model initially
            else:
                logging.info("Single model mode currently only works with custom models.")
        if not BackendType.is_valid(backend):
            raise ValueError(f"{backend} is not a valid backend type. Choose backend from {BackendType.valid_types()}")
        async with serve(
            functools.partial(self.recv_audio, backend=BackendType(backend), faster_whisper_custom_model_path=faster_whisper_custom_model_path),
            host,
            port,
        ):
          await asyncio.Future()

    def cleanup(self, websocket):
        """
        Cleans up resources associated with a given client's websocket.

        Args:
            websocket: The websocket associated with the client to be cleaned up.
        """
        if self.client_manager.get_client(websocket):
          self.client_manager.remove_client(websocket)
class ServeClientBase(object):
    RATE = 16000
    SERVER_READY = "SERVER_READY"
    DISCONNECT = "DISCONNECT"

    def __init__(
        self,
        client_uid,
        websocket,
    ):
        self.client_uid = client_uid
        self.websocket = websocket
        self.frames = b""
        self.timestamp_offset = 0.0
        self.frames_np = None
        self.frames_offset = 0.0
        self.text = []
        self.current_out = ""
        self.prev_out = ""
        self.t_start = None
        self.exit = False
        self.same_output_count = 0
        self.show_prev_out_thresh = (10)
        self.add_pause_thresh = (3)

        self.transcript = []
        self.send_last_n_segments = 5
        self.transcript_len = 0
        self.cnt = 0

        # threading
        self.lock = threading.Lock()
    async def speech_to_text(self):
      raise NotImplementedError

    def transcribe_audio(self,input_sample):
      raise NotImplementedError

    async def handle_transcription_output(self, result, duration):
      raise NotImplementedError

    def data_reset(self):
      self.transcript = []
      self.frames = b""
      self.timestamp_offset = 0.0
      self.frames_np = None
      self.frames_offset = 0.0
      self.text = []
      self.current_out = ""
      self.prev_out = ""
      self.t_start = None
      self.exit = False
      self.same_output_count = 0
      self.transcript_len = 0
      self.cnt = 0

    def add_frames(self, frame_np):
        """
        Add audio frames to the ongoing audio stream buffer.

        This method is responsible for maintaining the audio stream buffer, allowing the continuous addition
        of audio frames as they are received. It also ensures that the buffer does not exceed a specified size
        to prevent excessive memory usage.

        If the buffer size exceeds a threshold (45 seconds of audio data), it discards the oldest 30 seconds
        of audio data to maintain a reasonable buffer size. If the buffer is empty, it initializes it with the provided
        audio frame. The audio stream buffer is used for real-time processing of audio data for transcription.

        Args:
            frame_np (numpy.ndarray): The audio frame data as a NumPy array.

        """
        self.lock.acquire()
        if self.frames_np is not None and self.frames_np.shape[0] > 45*self.RATE:
            print("Frame Shifted!!")
            self.frames_offset += 60.0
            self.frames_np = self.frames_np[int(30*self.RATE):]
            # check timestamp offset(should be >= self.frame_offset)
            # this basically means that there is no speech as timestamp offset hasnt updated
            # and is less than frame_offset
            if self.timestamp_offset < self.frames_offset:
                self.timestamp_offset = self.frames_offset
        if self.frames_np is None:
            self.frames_np = frame_np.copy()
        else:
            self.frames_np = np.concatenate((self.frames_np, frame_np), axis=0)
        self.lock.release()

    def clip_audio_if_no_valid_segment(self):
        """
        Update the timestamp offset based on audio buffer status.
        Clip audio if the current chunk exceeds 30 seconds, this basically implies that
        no valid segment for the last 30 seconds from whisper
        """
        with self.lock:
            if self.frames_np[int((self.timestamp_offset - self.frames_offset)*self.RATE):].shape[0] > 90 * self.RATE:
                duration = self.frames_np.shape[0] / self.RATE
                self.timestamp_offset = self.frames_offset + duration - 5

    def get_audio_chunk_for_processing(self):
        """
        Retrieves the next chunk of audio data for processing based on the current offsets.

        Calculates which part of the audio data should be processed next, based on
        the difference between the current timestamp offset and the frame's offset, scaled by
        the audio sample rate (RATE). It then returns this chunk of audio data along with its
        duration in seconds.

        Returns:
            tuple: A tuple containing:
                - input_bytes (np.ndarray): The next chunk of audio data to be processed.
                - duration (float): The duration of the audio chunk in seconds.
        """
        with self.lock:
            samples_take = max(0, (self.timestamp_offset - self.frames_offset) * self.RATE)
            input_bytes = self.frames_np[int(samples_take):].copy()
        duration = input_bytes.shape[0] / self.RATE
        return input_bytes, duration

    def prepare_segments(self, last_segment=None):
        """
        Prepares the segments of transcribed text to be sent to the client.

        This method compiles the recent segments of transcribed text, ensuring that only the
        specified number of the most recent segments are included. It also appends the most
        recent segment of text if provided (which is considered incomplete because of the possibility
        of the last word being truncated in the audio chunk).

        Args:
            last_segment (str, optional): The most recent segment of transcribed text to be added
                                          to the list of segments. Defaults to None.

        Returns:
            list: A list of transcribed text segments to be sent to the client.
        """
        self.transcript_len = len(self.transcript)
        if len(self.transcript) >= self.send_last_n_segments:
            segments = self.transcript[-self.send_last_n_segments:].copy()
        else:
            segments = self.transcript.copy()
        if last_segment is not None:
            segments = segments + [last_segment]
            self.transcript_len += 1
            if len(segments) > self.send_last_n_segments:
              segments.pop(0)

        return segments

    def get_audio_chunk_duration(self, input_bytes):
        """
        Calculates the duration of the provided audio chunk.

        Args:
            input_bytes (numpy.ndarray): The audio chunk for which to calculate the duration.

        Returns:
            float: The duration of the audio chunk in seconds.
        """
        return input_bytes.shape[0] / self.RATE

    async def send_transcription_to_client(self, segments):
        """
        Sends the specified transcription segments to the client over the websocket connection.

        This method formats the transcription segments into a JSON object and attempts to send
        this object to the client. If an error occurs during the send operation, it logs the error.

        Returns:
            segments (list): A list of transcription segments to be sent to the client.
        """
        segments += [self.transcript_len]
        self.logger.debug(f"[send_transcription_to_client segments]: {segments} \n")
        try:
            await self.websocket.send(
                json.dumps({
                    "uid": self.client_uid,
                    "segments": segments,
                })
            )
        except Exception as e:
            logging.error(f"[ERROR]: Sending data to client: {e}")

    async def disconnect(self):
        """
        Notify the client of disconnection and send a disconnect message.

        This method sends a disconnect message to the client via the WebSocket connection to notify them
        that the transcription service is disconnecting gracefully.

        """
        await self.websocket.send(json.dumps({
            "uid": self.client_uid,
            "message": self.DISCONNECT
        }))

    def cleanup(self):
        """
        Perform cleanup tasks before exiting the transcription service.

        This method performs necessary cleanup tasks, including stopping the transcription thread, marking
        the exit flag to indicate the transcription thread should exit gracefully, and destroying resources
        associated with the transcription process.

        """
        logging.info("Cleaning up.")
        self.exit = True



class ServeClientFasterWhisper(ServeClientBase):
    SINGLE_MODEL = None
    SINGLE_MODEL_LOCK = threading.Lock()

    def __init__(
        self,
        websocket,
        task="transcribe",
        language=None,
        client_uid=None,
        model="small.en",
        initial_prompt=None,
        hotwords=None,
        single_model=False,
    ):
        """
        Initialize a ServeClient instance.
        The Whisper model is initialized based on the client's language and device availability.
        The transcription thread is started upon initialization. A "SERVER_READY" message is sent
        to the client to indicate that the server is ready.

        Args:
            websocket (WebSocket): The WebSocket connection for the client.
            task (str, optional): The task type, e.g., "transcribe". Defaults to "transcribe".
            device (str, optional): The device type for Whisper, "cuda" or "cpu". Defaults to None.
            language (str, optional): The language for transcription. Defaults to None.
            client_uid (str, optional): A unique identifier for the client. Defaults to None.
            model (str, optional): The whisper model size. Defaults to 'small.en'
            initial_prompt (str, optional): Prompt for whisper inference. Defaults to None.
            single_model (bool, optional): Whether to instantiate a new model for each client connection. Defaults to False.
            send_last_n_segments (int, optional): Number of most recent segments to send to the client. Defaults to 10.
            no_speech_thresh (float, optional): Segments with no speech probability above this threshold will be discarded. Defaults to 0.45.
            clip_audio (bool, optional): Whether to clip audio with no valid segments. Defaults to False.
            same_output_threshold (int, optional): Number of repeated outputs before considering it as a valid segment. Defaults to 10.

        """
        super().__init__(
            client_uid,
            websocket
        )
        self.model_sizes = [
            "tiny", "tiny.en", "base", "base.en", "small", "small.en",
            "medium", "medium.en", "large-v2", "large-v3", "distil-small.en",
            "distil-medium.en", "distil-large-v2", "distil-large-v3",
            "large-v3-turbo", "turbo"
        ]
        self.initial_prompt = initial_prompt
        self.hotwords = hotwords

        self.model_size_or_path = model
        self.language = "en" if self.model_size_or_path.endswith("en") else language
        self.task = task
        self.no_speech_thresh = SETTINGS["server"]["no_speech_thresh"]

        self.same_output_threshold = SETTINGS["server"]["same_output_threshold"]
        self.language_cnt_threshold = SETTINGS["server"]["language_cnt_threshold"]
        self.end_time_for_same_output = None

        device = "cuda" if torch.cuda.is_available() else "cpu"
        if device == "cuda":
            major, _ = torch.cuda.get_device_capability(device)
            self.compute_type = "float16" if major >= 7 else "float32"
        else:
            self.compute_type = "int8"

        self.compute_type = "float16"

        if self.model_size_or_path is None:
            return
        logging.info(f"Using Device={device} with precision {self.compute_type}")

        try:
            if single_model:
                if ServeClientFasterWhisper.SINGLE_MODEL is None:
                    self.create_model(device)
                    ServeClientFasterWhisper.SINGLE_MODEL = self.transcriber
                else:
                    self.transcriber = ServeClientFasterWhisper.SINGLE_MODEL
            else:
                self.create_model(device)
        except Exception as e:
            logging.error(f"Failed to load model: {e}")
            return

        log_dir = PROJECT_ROOT / "logs"
        os.makedirs(  log_dir, exist_ok=True)

        log_time = datetime.now().strftime("%Y%m%d_%H%M%S")
        log_file = os.path.join(log_dir, f"Server-log.{log_time}.log")

        self.logger = logging.getLogger("ServerLogger")
        if SETTINGS["log_status"]:
          self.logger.setLevel(logging.DEBUG)
        else:
          self.logger.setLevel(logging.CRITICAL)

        self.logger.propagate = False

        file_handler = logging.FileHandler(log_file, encoding="utf-8")
        file_handler.setLevel(logging.DEBUG)

        formatter = logging.Formatter(
            fmt="%(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        )
        file_handler.setFormatter(formatter)

        if not self.logger.handlers:
          self.logger.addHandler(file_handler)
        self.logger.info("Server initialized.")
        self.logger.debug(f"[Websocket Info]: {self.websocket}")

    async def init_stt_thread(self):
      await self.speech_to_text()
      await asyncio.sleep(0)
      await self.websocket.send(
          json.dumps(
              {
                  "uid": self.client_uid,
                  "message" : self.SERVER_READY,
                  "backend" : "faster_whisper"
              }
          )
      )

    def create_model(self, device):
        """
        Instantiates a new nodel, sets it as the transcriber.
        """

        model = WhisperModel(
            self.model_size_or_path,
            device=device,
            compute_type=self.compute_type,
            local_files_only=False,
            **SETTINGS["asr_model"]
        )
        self.transcriber = model

    async def check_valid_model(self,model_size):
      """
      Check if it's a valid whisper model size.
      args :
        model_size (str): The name of the model size to check.

      Returns:
        str : The model size if valid, None otherwise.
      """
      if model_size not in self.model_sizes:
        await self.websocket.send(
            json.dumps(
                {
                    "uid": self.client_uid,
                    "status": "ERROR",
                    "message":f"Invalid model size { model_size}. Available choices: {self.model_sizes}",
                }
            )
        )
        return None
      return model_size

    async def set_language(self, info):
        """
        Updates the language attribute based on the detected language information.

        Args:
            info (object): An object containing the detected language and its probability. This object
                        must have at least two attributes: `language`, a string indicating the detected
                        language, and `language_probability`, a float representing the confidence level
                        of the language detection.
        """
        if info.language_probability > 0.5:
            self.language = info.language
            # logging.info(f"Detected language {self.language} with probability {info.language_probability}")
            await self.websocket.send(json.dumps(
                {"uid": self.client_uid, "language": self.language, "language_prob": info.language_probability}))

    def transcribe_audio(self, input_sample) -> list:
        """
        Transcribes the provided audio sample using the configured transcriber instance.

        If the language has not been set, it updates the session's language based on the transcription
        information.

        Args:
            input_sample (np.array): The audio chunk to be transcribed. This should be a NumPy
                                    array representing the audio data.

        Returns:
            The transcription result from the transcriber. The exact format of this result
            depends on the implementation of the `transcriber.transcribe` method but typically
            includes the transcribed text.
        """
        if ServeClientFasterWhisper.SINGLE_MODEL:
            ServeClientFasterWhisper.SINGLE_MODEL_LOCK.acquire()

        self.initial_prompt = None

        segment_generator, info = self.transcriber.transcribe(
            input_sample,
            initial_prompt=self.initial_prompt,
            language=self.language if self.cnt >= self.language_cnt_threshold else None,
            task=self.task,
            hotwords=self.hotwords,
            **SETTINGS["transcribe"],
        )

        if ServeClientFasterWhisper.SINGLE_MODEL:
            ServeClientFasterWhisper.SINGLE_MODEL_LOCK.release()

        result = []
        if not segment_generator:
          return result

        for segment in segment_generator:
          segment.language = info.language
          result.append(segment)

        if self.cnt < self.language_cnt_threshold:
          if (
              info.language in ["en", "ko"] and info.language_probability > 0.9
          ):
            if self.cnt > 0 and self.language != info.language:
              self.cnt =1
            else:
              self.cnt += 1
            self.language = info.language
          else:
            self.cnt = 1

        return result

    def get_previous_output(self):
      segments = []
      if self.t_start is None:
        self.t_start = time.time()
      if time.time() - self.t_start < self.show_prev_out_thresh:
        segments = self.prepare_segments()

      if len(self.text) and self.text[-1] != "":
        if time.time() - self.t_start > self.add_pause_thresh:
          self.text.append("")

      return segments

    async def handle_transcription_output(self, result, duration):
        """
        Handle the transcription output, updating the transcript and sending data to the client.

        Args:
            result (str): The result from whisper inference i.e. the list of segments.
            duration (float): Duration of the transcribed audio chunk.
        """
        # ==========================================
        # 🔍 [DEBUG-SERVER-TEXT] 서버 오프셋과 Whisper가 뱉은 텍스트 확인
        # ==========================================
        if hasattr(self, 'logger') and result:
            texts = " | ".join([f"(local {s.start:.2f}~{s.end:.2f}: '{s.text}')" for s in result])
            self.logger.debug(f"[DEBUG-SERVER-TEXT] 현재 Offset: {self.timestamp_offset:.3f}s 👉 {texts}")
        # ==========================================

        self.logger.debug(f"[Result of whisper]: {result}\n")

        segments = []
        if len(result):
            self.t_start = None
            last_segment = self.update_segments(result, duration)
            self.logger.debug(f"[Result of update_segments]: {last_segment}\n\n")
            segments = self.prepare_segments(last_segment)

        if len(segments):
            await self.send_transcription_to_client(segments)
    async def speech_to_text(self):
      while True:
        await asyncio.sleep(0)
        if self.exit:
          logging.info("Exiting speech to text thread")
          break
        if self.frames_np is None:
          continue

        input_bytes, duration = self.get_audio_chunk_for_processing()
        if duration < 1.0:
          await asyncio.sleep(0.1)
          continue
        try:
            input_sample = input_bytes.copy()
            result = self.transcribe_audio(input_sample)
            if not result:
                self.timestamp_offset += duration
                await asyncio.sleep(0.1)
                continue
            await self.handle_transcription_output(result, duration)
            await asyncio.sleep(0)

        except Exception as e:
          logging.error(f"Error : Failed to transcribe audio chunk {e}")
          traceback.print_exc()
          await asyncio.sleep(0.01)

    @staticmethod
    def format_segment(start, end, text, lang, completed=False, forced = False)-> dict:
      return {
          "start" : "{:.3f}".format(start),
          "end": "{:.3f}".format(end),
          "text" : text,
          "completed" : completed,
          "lang" : lang,
          "forced" : forced,
      }

    def filtering_segments_by_prob(self,segment_list : List,prob_threshold : float = 0.2,recompute_text: bool = True,) -> Dict[str, Any]:
      if not segment_list:
        raise ValueError(
            "segment_list is empty; expected a single Segment inside a list."
        )
      seg = segment_list[0]

      orig_words = list(getattr(seg,"words",[]) or [])
      kept_words = []
      for w in orig_words:
        p = getattr(w, "probability", None)
        if p > prob_threshold:
          kept_words.append(w)

      try:
        seg.words = kept_words
      except Exception:
        pass

      if recompute_text:
        new_text = (
            "".join(getattr(w,"word","") for w in kept_words)
            if kept_words
            else ""
        )

        if new_text:
          try:
            seg.text = new_text
          except Exception:
            pass

      return [seg]

    def update_segments(self, segments, duration):
        """
        Processes the segments from Whisper and updates the transcript.
        Uses helper methods to account for differences between backends.

        Args:
            segments (list): List of segments returned by the transcriber.
            duration (float): Duration of the current audio chunk.

        Returns:
            dict or None: The last processed segment (if any).
        """
        offset = None
        self.current_out = ''
        last_segment = None

        # Process complete segments
        if len(segments) > 1 and segments[-1].no_speech_prob <= self.no_speech_thresh:
            for i,s in enumerate(segments[:-1]):
                text_ = s.text
                self.text.append(text_)
                with self.lock:
                    start, end = (
                    self.timestamp_offset + s.start,
                    self.timestamp_offset + min(duration, s.end),
                    )
                if start >= end:
                    continue
                if s.no_speech_prob > self.no_speech_thresh:
                    print("\n\ncuttttttt\n\n")
                    continue

                self.transcript.append(
                  self.format_segment(start,end,text_,s.language,completed=True)
                )
                self.language = None
                self.cnt = 0
                offset = min(duration, s.end)
        if segments[-1].no_speech_prob <= self.no_speech_thresh:
            self.current_out += segments[-1].text
            with self.lock:
              last_segment = self.format_segment(
                  self.timestamp_offset + segments[-1].start,
                  self.timestamp_offset + min(duration, segments[-1].end),
                  self.current_out,
                  segments[-1].language,
                  completed = False,
              )
        if self.current_out.strip() == self.prev_out.strip() and self.current_out != "":
            self.same_output_count += 1

            # if we remove the audio because of same output on the nth reptition we might remove the
            # audio thats not yet transcribed so, capturing the time when it was repeated for the first time
            if self.end_time_for_same_output is None:
                self.end_time_for_same_output = segments[-1].end
            time.sleep(0.1)  # wait briefly for any new voice activity
        else:
            self.same_output_count = 0
            self.end_time_for_same_output = None

        # If the same incomplete segment is repeated too many times,
        # append it to the transcript and update the offset.
        if self.same_output_count > self.same_output_threshold:
            if (
                not self.text
                or self.text[-1].strip().lower() != self.current_out.strip().lower()
            ):
                self.text.append(self.current_out)
                with self.lock:
                    self.transcript.append(
                        self.format_segment(
                            self.timestamp_offset + segments[-1].start,
                            self.timestamp_offset + min(duration, self.end_time_for_same_output),
                            self.current_out,
                            segments[-1].language,
                            completed = False,
                            forced = True,
                        )
                    )
                    self.language = None
                    self.cnt = 0
            last_segment = None
            self.current_out = ""
            offset = min(duration, self.end_time_for_same_output)
            self.same_output_count = 0
            self.end_time_for_same_output = None
        elif segments[-1].timestamp_forced_completion:
            if (
                not len(self.text)
                or self.text[-1].strip().lower() != self.current_out.strip().lower()
            ):
                print("timestamp_forced_completion")
                self.text.append(self.current_out)
                with self.lock:
                    self.transcript.append(
                        self.format_segment(
                            self.timestamp_offset + segments[-1].start,
                            self.timestamp_offset + min(duration, segments[-1].end),
                            self.current_out,
                            segments[-1].language,
                            completed = True,
                            forced = True,
                        )
                    )
                    self.language = None
                    self.cnt = 0
            last_segment = None
            self.current_out = ""
            offset = min(duration, segments[-1].end)
            self.same_output_count = 0
            self.end_time_for_same_output = None
        self.prev_out = self.current_out

        if offset is not None:
            with self.lock:
                self.timestamp_offset += offset
        return last_segment