# -*- coding: utf-8 -*-
"""translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fInN8qq1gNz82uNXzi3IDxS2gnz8G8os
"""

from dataclasses import dataclass
import httpx
import json
import os
import asyncio

from realtime_asr.filtering import get_prompt_manager

from qdrant_client import QdrantClient
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Qdrant
from realtime_asr.config import PROJECT_ROOT

class TranslatorBase:
    def __init__(self, model_name, client):
        self.model_name = model
        self.client = httpx.AsyncClient(timeout=None)

        self.LOCAL_EMBEDDING_MODEL_PATH = os.path.join(PROJECT_ROOT, "src", "realtime_asr", "filtering", "bge-m3")
        self.LOCAL_QDRANT_DB_PATH = os.path.join(PROJECT_ROOT, "src", "realtime_asr", "filtering", "local_qdrant_db")
        self.COLLECTION_NAME = "official_translation"

        self.embed = HuggingFaceEmbeddings(model_name=self.LOCAL_EMBEDDING_MODEL)
        self.qdrant_client = QdrantClient(path = self.LOCAL_QDRANT_DB_PATH)
        self.vector_store = Qdrant(
            client = self.qdrant_client,
            collection_name = self.COLLECTION_NAME,
            embeddings = self.embed
        )

    @staticmethod
    def get_status(completed):
        return "process" if not completed else "complete"

    @staticmethod
    def get_to_lang(language):
        return "ko" if language == "en" else "en"

    @staticmethod
    def convert_lang_formal(language):
        return "Korean" if language == "ko" else "English"

    async def connect(self):
        await self.client.__aenter__()
    async def close(self):
        if self.client and not self.client.is_closed:
            await self.client.__aexit__(None,None,None)

    async def translate(self, content, language):
        raise NotImplementedError

    def get_static_system_text(self, from_lang, to_lang):
            return f"""You are a military professional translator.
            Rules:
            1. Always translate the given {from_lang} content into natural, fluent, polite, and formal {to_lang}.
            2. Even if the input is incomplete, ambiguous, or contains typos, you must still produce a translation.
            3. Do not apologize, refuse, or output explanations. Never contain special token.
            4. Output only the final translated {to_lang}!!
            5. Use polite endings (e.g., -습니다, -ㅂ니다 for Korean).
            6. If start word of sentence is \"다음\", its means \"Next slide,\"
            7. when the context refers to Republic of Korea, convert similar-sounding words(rock, lock, rog, etc,) to Rok.
            8. \"sir\" is only a politeness marker. Ignore it and do not translate it.
            """

    def build_prompt(self, content, system_blocks):
        """system_blocks 리스트를 받아서 최종 프롬프트 문자열 생성"""
        full_system_content = "\n\n".join(system_blocks)
        analysis_instruction = f"We need to translate the following sentence into formal. using military terminology. Sentence: \"{content}\""

        return f"""<|start|>system<|message|>
        {full_system_content}<|end|>
        <|start|>user<|message|>
        {content}<|end|>
        <|start|>assistant<|channel|>analysis<|message|>
        {analysis_instruction}<|end|>
        <|start|>assistant<|channel|>final<|message|>
        """

    def get_fast_prompt(self, content, system_blocks):
        """analysis 채널 없는 경량 프롬프트"""
        full_system_content = "\n\n".join(system_blocks)

        return f"""<|start|>system<|message|>
        {full_system_content}<|end|>
        <|start|>user<|message|>
        {content}<|end|>
        <|start|>assistant<|channel|>final<|message|>
        """



class LlamaTranslator(TranslatorBase):

    async def translate(self, content, language):
        from_lang = TranslatorBase.convert_lang_formal(language)
        to_lang = TranslatorBase.convert_lang_formal(TranslatorBase.get_to_lang(language))

        system_blocks = [self.get_static_system_text(from_lang, to_lang)]

        # 풀 프롬프트에서만 추가되는 부분
        glossary_rules_text = f"""
            5. GLOSSARY PRIORITY: Strictly follow the provided GLOSSARY for technical military terms to ensure consistency.
            6. Contextual Translation: While following the glossary, ensure the overall sentence structure is grammatically correct in {to_lang}.
            """
        prompt_manager = get_prompt_manager()
        glossary_part = prompt_manager.get_relevant_glossary(content)
        sentence_part = prompt_manager.get_sentence_block()

        if glossary_part:
            system_blocks.append(glossary_rules_text.strip())
            system_blocks.append(glossary_part)
        if sentence_part:
            system_blocks.append(sentence_part)

        vector_search_results = await asyncio.to_thread(
            self.vector_store.similarity_search, content, k=3
        )
        if vector_search_results:
            system_blocks.append("### EXAMPLES")
            for doc in vector_search_results:
                system_blocks.append(f"{doc.metadata.get('source', '')} : {doc.metadata.get('target', '')}")

        prompt = self.build_prompt(content, system_blocks)
        async for chunk in self._stream(prompt):
            yield chunk

    async def translate_fast(self, content, language):
        from_lang = TranslatorBase.convert_lang_formal(language)
        to_lang = TranslatorBase.convert_lang_formal(TranslatorBase.get_to_lang(language))

        system_blocks = [self.get_static_system_text(from_lang, to_lang)]
        prompt = self.get_fast_prompt(content, system_blocks)
        async for chunk in self._stream(prompt):
            yield chunk

    async def _stream(self, prompt):
        """실제 HTTP 스트리밍 공통 처리"""
        try:
            async with self.client.stream(
                "POST",
                "http://localhost:2010/v1/completions",
                headers={"Content-Type": "application/json"},
                json={
                    "model": self.model_name,
                    "prompt": prompt,
                    "use_beam_search": False,
                    "n": 1,
                    "temperature": 0.0,
                    "max_tokens": 1024,
                    "top_p": 1,
                    "top_k": 0,
                    "repeat_penalty": 1,
                    "stream": False
                }
            ) as response:
                response.raise_for_status()
                async for line in response.aiter_lines():
                    if not line:
                        continue
                    line = line.strip()
                    if line.startswith("data:"):
                        line = line[len("data:"):].strip()
                    if line == "[DONE]":
                        break
                    try:
                        data = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    choices = data.get("choices") or []
                    chunk = choices[0]
                    text_piece = chunk.get("text", "")

                    if text_piece:
                        if "<" in text_piece:
                            yield f"data: {json.dumps({'status': 'done'}, ensure_ascii=False)}\n\n"
                            return

                        if ":" in text_piece:
                            last = text_piece.rfind('"')
                            if last != -1:
                                prev = text_piece.rfind('"', 0, last)
                                if prev != -1:
                                    text_piece = text_piece[prev + 1: last]

                        yield f"data: {json.dumps({'content': text_piece}, ensure_ascii=False)}\n\n"

        except Exception:
            pass

        yield f"data: {json.dumps({'status': 'done'}, ensure_ascii=False)}\n\n"

